### ISSUE TITLE
[Feature] Parametrize the ability to include only files.

### ISSUE THREAD

**Issue by Shaddy** [vishaltelangre/ff#14]
# Be able to exclude directories without using a regular expression.

## Description

There is an ambiguity between a file or folder. A file can have no extension, so there is no way using a regular expression to distinguish between a file or a folder.

e.g. `/home/user/ambigous_name` 

is it a file, or a folder? because ff will output this and there is no regular expression that can guarantee this to get filtered.

I did a simple test that gets the following output.

```
dev@rasp03:/home/dev/test $ ff .
.
./this_is_a_file
./this_is_a_folder
```

## Motivation

The reason for this is that I want to replace the default vim command for [https://github.com/ctrlpvim/ctrlp.vim](CtrlP) extension (for obvious reasons).

I am using the following, actually.

`let g:ctrlp_user_command = 'ff . %s -x "/$"'`

But unluckily it also includes directories. As an example, the default command will be the following.

`let g:ctrlp_user_command = 'find %s -type f'`

It could be a good start point as choicing the way/parameter name for this.

## Final

If you find this is already implemented or not relevant, please let me know so I can look for a workaround, and also thanks for this great tool!

**Comment by vishal-vineti** [comment]
@Shaddy The requirement seems legit. A flag such as `-F` should exclude the matched "only folder" paths from the result. Sounds good?

**Comment by vishaltelangre** [comment]
@Shaddy The requirement seems legit. A flag such as `-F` should exclude the matched "only folder" paths from the result. Sounds good?

**Comment by Shaddy** [comment]
Sounds awesome, thank you very much :)

**Comment by vishaltelangre** [comment]
The new version `v0.1.7` introduces `-D (--exclude-dir-paths)` flag to address this requirement.
