### ISSUE TITLE
Remove secrets from `.traivs`-file

### ISSUE THREAD

**Issue by dreampulse** [vishaltelangre/ff#5]
https://github.com/vishaltelangre/ff/blob/afcf61fffbfa86ef5b186315a1613977f5531d98/.travis.yml#L68

**Comment by vishaltelangre** [comment]
It is an encrypted secret, seems to be safe as per https://docs.travis-ci.com/user/encryption-keys/. This is used to upload the precompiled cross-platform binaries on TravisCI to https://github.com/vishaltelangre/ff/releases page.

Fyi, the original `.travis.yml` template is copied from https://github.com/japaric/trust/blob/bbeaa9b8282f5faf2a2e276d41e2960082edbd2b/.travis.yml#L103-L108.

Feel free to suggest an alternative approach.
